### ISSUE TITLE
[Bug]: Failed while running tests

### ISSUE THREAD

**Issue by naveensrinivasan** [gittuf/gittuf#160]
### What happened?

=== RUN   TestVerifyCommitSignature
=== RUN   TestVerifyCommitSignature/use_gpg_signed_commit_with_gitsign_key
    commit_test.go:115: 
        	Error Trace:	/Users/naveen/go/src/github.com/naveensrinivasan/gittuf/internal/gitinterface/commit_test.go:115
        	Error:      	Target error should be in err chain:
        	            	expected: "incorrect key provided to verify signature"
        	            	in chain: "unable to verify Sigstore signature\ninitializing tuf: unable to initialize client, local cache may be corrupt: tuf: error unmarshalling key: invalid PEM value"
        	Test:       	TestVerifyCommitSignature/use_gpg_signed_commit_with_gitsign_key
--- FAIL: TestVerifyCommitSignature (0.03s)
    --- FAIL: TestVerifyCommitSignature/use_gpg_signed_commit_with_gitsign_key (0.02s)

FAIL

Process finished with the exit code 1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityasaky** [comment]
@naveensrinivasan thanks for filing this! Did you encounter this after cloning the repo and running `go test` / `make` locally? Can you provide some information regarding the environment you ran this in? Also, are you able to reproduce this?

@wlynch I think this ties into #73, this test is effectively "live" because it tries to update the embedded root.json in sigstore/sigstore I think. For a start, maybe we ought to disable this test and / or add some checks to see if the key type of the verification key matches signature type (I'd have to poke around to find out what git stores here) before invoking the actual verification workflow for gitsign / gpg.

**Comment by naveensrinivasan** [comment]
I am consistently able to reproduce this. I am on Mac OS Sonama.

**Comment by adityasaky** [comment]
Thanks!

**Comment by wlynch** [comment]
This is coming from https://github.com/sigstore/sigstore/blob/7a4071154b0c752513bde4b2584d59e7da0ecb73/pkg/tuf/client.go#L304 - based on the error, there's something unexpected in your Sigstore TUF repo layout. 🤔  (I can't repro this, also on Sonoma)

Quick fix is probably: 

```sh
$ rm -rf ~/.sigstore
$ gitsign initialize
```

(`cosign initialize` would also work)

**Comment by naveensrinivasan** [comment]
This solved the issue. Thanks
