### ISSUE TITLE
Getting started error with gittuf trust init: Error: invalid character '-' in numeric literal

### ISSUE THREAD

**Issue by nealmcb** [gittuf/gittuf#360]
### What happened?

I followed the instructions at https://github.com/gittuf/gittuf/blob/main/docs/get-started.md
I'm running this version:

```
$ gittuf version
gittuf version 0.3.0
```

It all seemed to go well until I got to

```
$ gittuf trust init -k ../keys/root
Error: invalid character '-' in numeric literal
```

The command `gittuf help trust init` includes this hint:
`-k, --signing-key string`   signing key to use to sign root of trust

in which the word `string` doesn't seem to match the demo using a file name. But substituting an arbitrary string makes it clear that it is looking for a file name: `Error: open abc: no such file or directory`. And indeed, the given file does start with a `-`:
`-----BEGIN OPENSSH PRIVATE KEY-----`

So besides the initial invalid character error, it seems that the help documentation could be improved.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityasaky** [comment]
Hi @nealmcb, thanks for flagging this! To confirm, you created new keys while following the guide, yes? Is the key encrypted by any chance? We have a major hole at the moment (#276) that I'm planning to address starting Wednesday with reading encrypted keys by prompting the user for a passphrase.

**Comment by lukpueh** [comment]
Similar problem here, although, I'm getting the error message one command later when following the "Getting started" guide. 

Maybe because I built from the main branch...

```bash
$ gittuf version
gittuf version 0.3.0-173-g1a0878a

# ... create (unencrypted!) keys and repo as per Getting Started

$ gittuf trust init -k ../keys/root
Signing data on standard input
Signing data on standard input

$ gittuf trust add-policy-key -k ../keys/root --policy-key ../keys/policy.pem
Error: invalid character '-' in numeric literal
```

**Comment by lukpueh** [comment]
used keys were:

[keys.tar.gz](https://github.com/gittuf/gittuf/files/15234959/keys.tar.gz)

cc @adityasaky

**Comment by neilnaveen** [comment]
This worked fine for me, though instead of using keys/policy.pem, which I cannot find in my keys folder, I am using the targets.pem key 

<img width="962" alt="Screenshot 2024-05-07 at 9 16 52 AM" src="https://github.com/gittuf/gittuf/assets/42328488/0aaf1726-eae8-4e12-8613-df4ac70a556a">

**Comment by nealmcb** [comment]
Sorry for the delay. Yes, @adityasaky, I provided a password for the keys, as I assume anyone would. I'm sorry I missed the note in the _Get Started_ document that indeed says **gittuf does not currently support encrypted private keys**. Since some folks may better understand it in terms of the way the interface is worded, I've proposed changing that text to mention passphrases explicitly in #387.

**Comment by adityasaky** [comment]
Thanks for clarifying! We haven't had a chance yet to look at where @lukpueh ran into trouble, so I'll leave this open for now.

**Comment by lukpueh** [comment]
Looks like my problem is a Mac problem. My `ssh-keygen` gives me a public ecdsa key with "explicit parameters"  that go can't read (it expects a "named curve"). I'm using:

```bash
$ ssh -V
OpenSSH_9.6p1, LibreSSL 3.3.6
```

A quick fix for both problems described here would be to replace `ssh-keygen` with `openssl` in the snippet, which seems to generate keys that work on Mac and linux (at least with the versions I tried), and can be configured so that the user isn't prompted for a password.

Independently, I will open an issue to improve error messaging. The reason why we both got the same error message for very different reasons (Neal, while loading a private key in `trust init`; me, while loading a public key in `trust add-policy-key`) is that we both ended up in [`parsePEMKey`](https://github.com/gittuf/gittuf/blob/232289e892b4479bafa5c835e4fafcbc5d0e2f8e/internal/third_party/go-securesystemslib/signerverifier/utils.go#L127-L153), which tries several different formats to load any key, the last of which is the proprietary securesystemslib legacy format, which expects json and chokes on the leading dashes.

**Comment by adityasaky** [comment]
> A quick fix for both problems described here would be to replace ssh-keygen with openssl in the snippet, which seems to generate keys that work on Mac and linux (at least with the versions I tried), and can be configured so that the user isn't prompted for a password.

This would work well for most of the signing operations, but we also use the key for git signing in the guide. We `git config --local user.signingkey` one of the ssh keys. :thinking:

**Comment by lukpueh** [comment]
> Maybe for the short term, we should just update the guide to use RSA keys?

That should work.

**Comment by adityasaky** [comment]
Thanks, everyone!
